language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower'
  - 'bower install'
  - 'npm run install'
  - 'gulp'
  - 'travis_setup.sh'

notifications:
  on_success: change
  on_failure: always