language: node_js
node_js:
  - '0.10'
before_script:
  - 'npm install -g bower'
  - 'bower install'
  - 'npm run install'
  - 'webdriver-manager start'
  - 'gulp'

notifications:
  on_success: change
  on_failure: always